# Generated by Django 5.2.17 on 2026-08-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_zone_booking_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='capacity',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='zone',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='type',
            field=models.CharField(choices=[('ordinary', 'Oddiy'), ('vip', 'VIP')], default='ordinary', max_length=20),
        ),
    ]
